syntax = "proto3";

package log.v1;

option go_package = "github.com/Devin-Yeung/proglog/api/log_v1";

message Record {
  bytes value = 1;
  uint64 offset = 2;
}

message ProduceRequest {
  Record record = 1;
}

message ProduceResponse {
  uint64 offset = 1;
}

message ConsumeRequest {
  uint64 offset = 1;
}

message ConsumeResponse {
  Record record = 1;
}

service Log {
  rpc Produce(ProduceRequest) returns (ProduceResponse) {}
  rpc Consume(ConsumeRequest) returns (ConsumeResponse) {}
  // Client send the starting offset and server sends a stream of records starting from that offset. The stream will not
  // end even if the server has sent all existing records, it will continue to send new records as they are produced.
  // The api is aim to allow clients to behave like `tail -f` command.
  rpc ConsumeStream(ConsumeRequest) returns (stream ConsumeResponse) {}
  // Client sends a stream of records to be produced and server responds with a stream of offsets for each produced record
  rpc ProduceStream(stream ProduceRequest) returns (stream ProduceResponse) {}
}